{{- if and .Values.nginxGateway.metrics.enable .Values.nginxGateway.metrics.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-gateway.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ include "nginx-gateway.fullname" . }}-metrics
    {{- include "nginx-gateway.labels" . | nindent 4 }}
{{- if .Values.nginxGateway.metrics.service.labels }}
{{ toYaml .Values.nginxGateway.metrics.service.labels | indent 4 }}
{{- end }}
{{- if .Values.nginxGateway.metrics.service.annotations }}
  annotations:
{{ toYaml .Values.nginxGateway.metrics.service.annotations | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "nginx-gateway.selectorLabels" . | nindent 4 }}
  ports:
  - name: metrics
    port: {{ .Values.nginxGateway.metrics.port }}
    protocol: TCP
    targetPort: {{ .Values.nginxGateway.metrics.port }}
{{- end }}
