{{- if and .Values.nginxGateway.metrics.enable .Values.nginxGateway.metrics.serviceMonitor.create }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nginx-gateway.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "nginx-gateway.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ include "nginx-gateway.fullname" . }}-metrics
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  {{- toYaml .Values.nginxGateway.metrics.serviceMonitor.endpoints | nindent 4 }}
{{- end }}
